# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/PHP.gitlab-ci.yml

# Select image from https://hub.docker.com/_/php/
image: $IMAGE:$PHP_VERSION

# Select what we should cache between builds
cache:
  paths:
    - vendor/

before_script:
  - cp tests/example-env-ci .env
  - composer install

# Bring in any services we need http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
# See http://docs.gitlab.com/ee/ci/services/README.html for examples.
services:
  - mysql:5.7

# Set any variables we need
variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  DB_USERNAME: $DATABASE_USER
  DB_HOST: mysql
  DB_SERVER: mysql
  DB_DRIVER: mysql
  DB_DATABASE: $DATABASE_NAME
  DB_PASS: $DATABASE_PASSWORD
  MYSQL_DATABASE: $DATABASE_NAME
  MYSQL_ROOT_PASSWORD: $DATABASE_PASSWORD
  IMAGE: "gitlab.creode.co.uk:5050/john.cook/docker-test"
  PHP_VERSION: "7.4"

# Run our tests
# If Xdebug was installed you can generate a coverage report and see code coverage metrics.
test:
  script:
    - php vendor/bin/codecept run
