name: Create Release

on: 
  workflow_dispatch:
    branches: [ 1.x ]

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Setup Commit User
      run: |
        git config --local user.email "creode-dev@users.noreply.github.com"
        git config --local user.name "Creode Developer"

    - name: Push Release
      run: |
        composer run-script release
        git push --tags origin HEAD